### ISSUE TITLE
Create code mono repo for easy development/deployment

### ISSUE THREAD

**Issue by the-jake-z** [8451/code-web-ui#10]
- Combine BFF/Service layers (BFF not really needed since there's only one Code service)
    - Need to move the Web Socket handling, configuration, and tests in the BFF
- Move the combined BFF/Service into code-web-ui project under a /service folder
- Move the current Web UI root files to a /ui folder
- Update Travis to use the build matrix a la: https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
- Add a docker compose file with all the necessary goodies to spin up a development environment with 1 command.
- Rename code-web-ui GitHub to "CoDE"
- Remove the old BFF and Service Repos

**Comment by tomdantuit** [comment]
Closing this issue because [a new mono repo has been created](https://github.com/8451/code). The work to combine the BFF and Service as well as docker-compose file are handled with issues  [1](https://github.com/8451/code/issues/1) and [2](https://github.com/8451/code/issues/2)
